name: fisioflow
region: nyc
services:
- name: web
  source_dir: /
  github:
    repo: rafaelminatto1/fisioflow-aistudio
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 3000
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  - key: PORT
    value: "3000"
  - key: HOSTNAME
    value: "0.0.0.0"
  - key: SKIP_ENV_VALIDATION
    value: "true"
  # Database variables (will be auto-configured by DO)
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DIRECT_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  # Auth variables
  - key: NEXTAUTH_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXTAUTH_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  # Optional variables
  - key: LOG_LEVEL
    value: info
  - key: HEALTH_CHECK_ENABLED
    value: "true"
  - key: RATE_LIMIT_ENABLED
    value: "true"
  - key: COMPRESSION_ENABLED
    value: "true"
databases:
- engine: PG
  name: fisioflow-db
  num_nodes: 1
  size: db-s-1vcpu-1gb
  version: "15"