name: fisioflow
region: nyc
services:
- name: web
  source_dir: /
  github:
    repo: rafaelminatto1/fisioflow-aistudio
    branch: main
    deploy_on_push: true
  build_command: |
    npm install
    npx prisma generate
    npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 3000
  health_check:
    http_path: /api/status
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  - key: PORT
    value: "3000"
  - key: HOSTNAME
    value: "0.0.0.0"
  - key: SKIP_ENV_VALIDATION
    value: "true"
  # Database variables (configure with real values)
  - key: DATABASE_URL
    value: postgresql://username:password@host:25060/database?sslmode=require&pool_timeout=30
  - key: DIRECT_URL
    value: postgresql://username:password@host:25060/database?sslmode=require
  # Auth variables (generate secure values)
  - key: NEXTAUTH_SECRET
    value: REPLACE_WITH_SECURE_SECRET
  - key: NEXTAUTH_URL
    value: https://fisioflow-app.ondigitalocean.app
  # Optional variables
  - key: LOG_LEVEL
    value: info
  - key: HEALTH_CHECK_ENABLED
    value: "true"
  - key: RATE_LIMIT_ENABLED
    value: "true"
  - key: COMPRESSION_ENABLED
    value: "true"
databases:
- engine: PG
  name: fisioflow-db
  num_nodes: 1
  size: db-s-1vcpu-1gb
  version: "15"