# Railway Nixpacks configuration for Next.js standalone
[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.build]
cmds = [
  "npm ci --only=production",
  "npx prisma generate", 
  "npm run build",
  "cp -r public .next/standalone/",
  "cp -r .next/static .next/standalone/.next/"
]

[phases.start]
cmd = "cd .next/standalone && node server.js"

[static]
dir = "public"