[build]
builder = "NIXPACKS"
command = "npm run build"

[deploy]
command = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
healthcheckInterval = 30
healthcheckRetries = 5
healthcheckDelay = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Neon DB specific configurations
[deploy.env]
NEON_POOLED_CONNECTION = "true"
NEON_CONNECTION_TIMEOUT = "30000"
NEON_IDLE_TIMEOUT = "600000"
NEON_MAX_CONNECTIONS = "20"
NEON_MIN_CONNECTIONS = "2"

# Configurações de recursos otimizadas para Neon DB
[resources]
cpu = 1000  # 1 vCPU
memory = 1024  # 1GB RAM

# Auto-scaling configuration
[scaling]
minReplicas = 1
maxReplicas = 3
targetCPUUtilization = 70
targetMemoryUtilization = 80

# Neon DB monitoring
[monitoring]
metricsPath = "/api/neon/metrics"
logsRetention = "7d"
healthCheckEnabled = true
neonMonitoringEnabled = true

# Variáveis de ambiente específicas do Railway
[env]
NODE_ENV = "production"
PORT = "3000"
HEALTH_CHECK_ENABLED = "true"
LOG_LEVEL = "info"
DATABASE_POOL_SIZE = "10"
DATABASE_TIMEOUT = "30000"
SESSION_TIMEOUT = "86400"
RATE_LIMIT_ENABLED = "true"
CORS_ENABLED = "true"