name: fisioflow
services:
- name: web
  image:
    registry_type: DOCKER_HUB
    repository: nginx
    tag: alpine
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: DATABASE_URL
    value: postgresql://doadmin:AVNS_4zgOHhDU6UGzIe8OlTg@fisioflow-production-db-do-user-25633309-0.m.db.ondigitalocean.com:25060/defaultdb?sslmode=require
  - key: NEXTAUTH_SECRET
    value: your-nextauth-secret-here-32-chars-min
  - key: NEXTAUTH_URL
    value: https://fisioflow-xxxxx.ondigitalocean.app