name: fisioflow
region: nyc1
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
services:
- name: web
  source_dir: /
  github:
    repo: rafaelminatto1/fisioflow-aistudio
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 3000
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    scope: RUN_AND_BUILD_TIME
    value: "1"
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "3000"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXTAUTH_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXTAUTH_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PRISMA_GENERATE_DATAPROXY
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: SKIP_ENV_VALIDATION
    scope: RUN_AND_BUILD_TIME
    value: "true"
databases:
- name: fisioflow-db
  engine: PG
  version: "14"
  size: db-s-1vcpu-1gb