name: fisioflow
services:
- name: web
  source_dir: /
  github:
    repo: rafaelminatto1/fisioflow-aistudio
    branch: main
  run_command: npm start
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: Dockerfile
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXTAUTH_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: NEXTAUTH_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ANTHROPIC_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: STRIPE_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: STRIPE_PUBLISHABLE_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: WHATSAPP_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: WHATSAPP_VERIFY_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3

databases:
- name: fisioflow-db
  engine: PG
  version: "14"
  size: basic-xs
  num_nodes: 1

region: nyc