name: fisioflow
services:
- name: web
  source_dir: /
  github:
    repo: rafaelminatto1/fisioflow-aistudio
    branch: main
  dockerfile_path: Dockerfile
  run_command: npm start
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 3000
  routes:
  - path: /
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  - key: PORT
    value: "3000"
  - key: DATABASE_URL
    value: postgresql://doadmin:AVNS_4zgOHhDU6UGzIe8OlTg@fisioflow-production-db-do-user-25633309-0.m.db.ondigitalocean.com:25060/defaultdb?sslmode=require
  - key: NEXTAUTH_SECRET
    value: your-nextauth-secret-here-32-chars-min
  - key: NEXTAUTH_URL
    value: ${APP_URL}